@startuml  Q2
actor Blackstone
actor whitestone
' subscribe the subject 2
Blackstone  -> subject2: attach  ip=192.168.1.100
whitestone  -> subject2: attach  ip=192.168.100.2
subject2->subject2: get state
subject2->subject2: set price
subject2->Blackstone: notify
subject2->whitestone: notify
' blackstone cancel the subscribe
Blackstone  -> subject2: detach  
subject2->subject2: set price
subject2->whitestone: notify
subject2->subject2: get state

@enduml